spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebanking_db
    username: postgres
    password: @aahmhmm28
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect.org.hibernate.dialect: PostgreSQLDialect

  security:
    sessions: stateless

logging:
  level:
    org.springframework.security: TRACE